#!/bin/sh

to_hash() {
  local sha1sum=""
  for sha1sum in sha1sum shasum sha1 ; do
    which "$sha1sum" >/dev/null 2>&1 && break
  done
  tr 'a-z' 'A-Z' | "$sha1sum" | cut -d' ' -f1
}

main() {
  local username="$1" password="$2"

  while [ -z "$(echo "$username" | tr -d " ")" ] || [ ${#username} -gt 32 ]; do
    echo -n "Username: "
    read -r username
    username="$(echo -n "$username" | tr -d '\n')"
    if [ "${#username}" -gt 16 ]; then
      >&2 echo "Username is too long; maximum length is 32 characters!"
    fi
  done

  while [ -z "${password}" ] || [ ${#password} -gt 16 ]; do
    echo -n "Password: "
    stty -echo; read -r password; stty echo
    password="$(echo -n "$password" | tr -d '\n')"
    echo
    if [ "${#password}" -gt 16 ]; then
      >&2 echo "Password is too long; maximum length is 16 characters!"
    fi
  done

  printf "$username:$password" | to_hash
}

main "$@"

